### ISSUE TITLE
Outline Demo not generating complete outlines

### ISSUE THREAD

**Issue by Iaknihs** [GDQuest/godot-shaders#22]
**I'm submitting a...**

- [X] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
The Outline3D demo scene creates incomplete outlines in Godot v3.2.2. Only 2 of the 5 shapes actually have a complete outline with others showing parts of the outline generated from surfaces, which don't link up properly.

**What is the expected behavior?**
The Outline3D demo should create actual outlines.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. Open the Demo Project in Godot v3.2.2.
2. Run Outline3DScene.tscn
3. Hover over the shapes

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information**

**Comment by NathanLovato** [comment]
That's intentional, this demo shows the various way you could go about calculating 3D outlines from 3D meshes and their caveats. Because depending on the model's shape and edge splits, the offsets

The only ways I know to get very crisp and precise outlines on 3D objects involve:

- Doing the outline in clip space, which is shown by the PixelPerfectOutline3D demo.
- Doing the outline in 2D, by rendering some 3D geometry (e.g. characters, interactive objects) to a viewport and doing post processing on the generated texture.
- Making a dedicated outline mesh, per object, which Godot can generate for you in the editor. That mesh is designed to be perfect for an outline, but you need to make one extra mesh manually for each object you want to outline, so it wouldn't work for a toon game.

I'm tweaking the demo's message to clarify this and that should close the issue.
